import { createSlice } from "@reduxjs/toolkit";


const FoodItemDataSlice = createSlice({
    name:"FoodItem",
    initialState:{foodData:[
        { id:"1",Name:"Malai Paneer",desc:"This recipe of Malai Paneer is a soft, melt-in-mouth and restaurant style dish made with paneer cubes, onions, cream, herbs and spices.",desc2:"Malai Paneer, as the name suggests, it’s a paneer curry prepared in a fresh milk cream based rich and spicy gravy where almond and cashew nut paste brings in rich texture while dried fenugreek leaves bring a subtle but definite flavor. Whether you are hosting a party at home or just looking for easy recipes with paneer to have a delicious quick Indian dinner, it’s a perfect choice to satisfy your craving for something spicy yet creamy.",price:69.00,rating:"Rating 4.0",img:require("../Assets/images/Malai-Paneer.jpg")},
        { id:"2",Name:"Dal-fry",desc:"Dal Fry is a delicious and popular Indian dish made with lentils (toor dal), onions, tomatoes, spices and herbs. Dal refers to lentils and are ...",desc2:"Dal Fry is a delicious and popular Indian lentil recipe that is made with tuvar dal (pigeon pea lentils), onions, tomatoes and spices. Relish this flavorful, mildly-spiced, creamy lentil dish with roti, naan or your favorite steamed rice.",price:59.00,rating:"Rating 4.0",img:require("../Assets/images/dal-fry.jpg")},
        { id:"3",Name:"Chapati",desc:"Chapati is the quintessence of the Indian cuisine so much so that no meal is complete without this Indian flatbread.",desc2:"Tawa Roti is a type of Indian flatbread fried crisp on a traditional iron girdle called Tawa. Its dough consists of whole wheat flour, water, oil, and salt. This dough is rolled into flat circles and then roasted until entirely cooked on the Tawa.",price:8.00,rating:"Rating 4.0",img:require("../Assets/images/chapati.jfif")},
        { id:"4",Name:"Curd",desc:"Curd is a traditional fermented dairy product that originated in Indian Sub-Continent. The word “dahi” may have derived from the Sanskrit word “ ...",desc2:"Curd is obtained by coagulating milk in a sequential process called curdling. It can be a final dairy product or the first stage in cheesemaking. The coagulation can be caused by adding rennet, a culture, or any edible acidic substance such as lemon juice or vinegar, and then allowing it to coagulate. The increased acidity causes the milk proteins (casein) to tangle into solid masses, or curds. Milk that has been left to sour (raw milk alone or pasteurized milk with added lactic acid bacteria) will also naturally produce curds, and sour milk cheeses are produced this way. Producing cheese curds is one of the first steps in cheesemaking; the curds are pressed and drained to varying amounts for different styles of cheese and different secondary agents (molds for blue cheeses, etc.) are introduced before the desired aging finishes the cheese. The remaining liquid, which contains only whey proteins, is the whey. In cow's milk, 90 percent of the proteins are caseins. Curds can be used in baking or may be consumed as a snack.",price:40.00,rating:"Rating 4.0",img:require("../Assets/images/curd.webp")},
        { id:"5",Name:"Sweet",desc:"Spongy Rasgulla is one of the popular Indian sweet recipes that is made by curdling milk. Then separating the chenna paneer or indian cottage ...",desc2:"Rasgulla (literally syrup filled roll) is a syrupy dessert popular in the eastern part of South Asia. It is made from ball-shaped dumplings of chhena and semolina dough, cooked in light sugar syrup made of sugar. This is done until the syrup permeates the dumplings.",price:22.00,rating:"Rating 4.0",img:require("../Assets/images/sweet.webp")},
        { id:"6",Name:"Mango pickle",desc:"Mango pickle is a spicy condiment made with raw mango, spice powders, salt, garlic & oil. This instant pickle is the best to make easily.",desc2:"Mango season in India is so famous that it has become a synonymous word for summer season. Here in India, very soon the mango season starts women in many households get ready to make enough mango pickle to last for the next few months. It is equally popular in the north or the south, east or west and enjoyed by everyone whether young or old. Spike your food with mango pickle eat it with rice, its sour and hot taste titillates the taste buds. The mouthwatering pickle is made from raw mangoes, mixed with chili and oil, garlic and a concoction of seeds like mustard and fenugreek. Raw mango is cut into small pieces, mixed with spices and seeds and stored in jars.",price:29.00,rating:"Rating 4.0",img:require("../Assets/images/mango-pickle.webp")},
    ]},
    reducers:{
        foodItem(state,action){
            state.foodData = action.payload
        }
    }
});

export const action = FoodItemDataSlice.actions;

export default FoodItemDataSlice;